@RPCServer_HostAddress = https://localhost:5000
@RPCServer_WebSocketAddress = ws://localhost:5000

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

JsonRPC: 2.0
Method: hello
Params:
  name: choi 0 hwan
Id: 1
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "JsonRPC":"2.0",
  "Method":"hello",
  "Params":{"name":"karin"},
  "Id":1
}
###

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

JsonRPC: 2.0
Method: add
Params:
  left: 53
  right: 12
Id: 1
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"add",
  "Params":{"left":131, "right":30},
  "Id":1
}
###