@RPCServer_HostAddress = https://localhost:5000
@RPCServer_WebSocketAddress = ws://localhost:5000

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

Method: hello
Params:
  name: world
Id: 1
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"hello",
  "Params":{"name":"world"},
  "Id":1
}
###

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

Method:
Params:
  name: world
Id: 2
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"",
  "Params":{"name":"world"},
  "Id":2
}
###

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

Method: hello
Params:
  name: 
Id: 3
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"hello",
  "Params":{"name":""},
  "Id":3
}
###

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

Method: hello
Params:
  
Id: 4
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"hello",
  "Params":{},
  "Id":4
}
###

POST {{RPCServer_HostAddress}}/rpc?in=yaml&out=yaml
Content-type:application/x-yaml

Method: hello
Id: 4
###

POST {{RPCServer_HostAddress}}/rpc
Content-type:Application/json

{
  "Method":"hello",
  "Id":4
}
###